[features]
seeds = false
skip-lint = false
[programs.devnet]
vrf_starter = "HofEGgj4wYPfPLoBJ42Q4rWM9QTLprHHXhTNXfRSJ9hP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.genesysgo.net"
wallet = "/Users/sven/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
